CREATE TABLE [dbo].[AssumptionStatus](
	[Id] [int] NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[IsFinalState] [bit] NOT NULL,
 CONSTRAINT [PK_AssumptionStatus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 

GO
